### ISSUE TITLE
Remove the letter 'a' from the legend

### ISSUE THREAD

**Issue by atsyplenkov** [kassambara/ggpubr#106]
Hey, I know that there's a bunch of questions at stackoverflow but however I still cannot find a solution.

How can I can remove the letter 'a' from the legend generated by `ggscatter`? Here is a slightly modified example from `ggpubr` [vignette](http://www.sthda.com/english/rpkgs/ggpubr/reference/ggscatter.html#examples). I've just added parameters to remove text element from a legend: `show.legend.text = F` and it's not working!

```
df <- mtcars
df$name <- rownames(df)
ggscatter(df, x = "wt", y = "mpg",
   color = "cyl", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
   label = "name", repel = TRUE, show.legend.text = F)

```

![rplot](https://user-images.githubusercontent.com/34775595/44430133-79b52600-a5a2-11e8-9fcb-1800b93f386d.png)

**Comment by kassambara** [comment]
fixed now, thanks

**Comment by teaelleceecee** [comment]
I know this issue has been closed but I am still having issues with this: 

df <- scatter_plot_data
df$Virus <- as.factor(df$Virus)

ggscatter(df, x = "Copies_per_uL", y = "RPKM",
          xlab = "Virus copies/uL", ylab = "Viral RPKM",
          xscale = "log10", format.xscale = TRUE, 
          yscale = "log10", format.yscale = TRUE,
          add = "reg.line",
          color = "Virus", palette = "jco",
          shape = "Virus",
          show.legend.text = FALSE,
          fullrange = TRUE
          )+
  stat_cor(aes(color = Virus), method = "spearman")

And this is the plot I get:
![image](https://user-images.githubusercontent.com/25648603/52928936-44916100-3396-11e9-8c5e-d4f73055d097.png)

**Comment by YinanZheng** [comment]
Same here. I have tried the latest release version and the latest github version. 

p1 <- ggscatter(all_amish_rmAffected, x = "PAI_1", y = "DNAmGrimAge_clean",
                color = "genotype", palette = "jco",
                add = "reg.line", conf.int = TRUE)
p1 + stat_cor(aes(color = genotype), label.x = 30)

**Comment by WellJoea** [comment]
try:
guides(color = guide_legend(override.aes = list(size = 5)))

**Comment by kassambara** [comment]
Please, consider specifying the option `show.legend = FALSE` when calling `stat_cor()` as below

``` r
suppressPackageStartupMessages(library(ggpubr))

df <- mtcars
df$name <- rownames(df)
df$cyl <- as.factor(df$cyl)


ggscatter(df, x = "wt", y = "mpg",
          color = "cyl", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          label = "name", repel = TRUE, show.legend.text = FALSE) +
  stat_cor(aes(color = cyl), method = "spearman", label.x = 4, show.legend = FALSE)
```

![](https://i.imgur.com/EVQYcZm.png)

**Comment by piiskop** [comment]
@WellJoea, your suggestion does not change a thing. Have you tried it? What is even the purpose of limiting a list size? A hack instead of a real solution?

@kassambra, your suggestion works kind of. It forbids displaying a legend. This is not a solution. i want a legend. Without these irrelevant _a_'s. Can you make it work without any hacks? Like, real programmers, do they consider all the possible options if a new thing is about to be developed. i am so depressed because of poor software. It is regulated in society that poor houses are not allowed. Unfortunately, poor software is. It does not matter that you did it for free. we all do. i do not want even to imagine producing a poor piece of software. What i publish is fully tested. i expect the same from you. From everyone. Quality matters.
