### ISSUE TITLE
How can I have correct format for label ? wrong custom label

### ISSUE THREAD

**Issue by bvprod2** [kassambara/ggpubr#120]
Dataset
![image](https://user-images.githubusercontent.com/22626187/47074191-2fdf6980-d1fa-11e8-97b3-af6f909b8f2c.png)

Wrong value in label using:
ggbarplot(df,x="x",y="y",fill="test", label = df$y,position = position_dodge(.75))
![image](https://user-images.githubusercontent.com/22626187/47073950-afb90400-d1f9-11e8-9874-99bfa1b12395.png)
Correct value using but cannot be formatted:
ggbarplot(CADdf2,x="coro",y="perc",fill="test", label = T,position = position_dodge(.75))

I want to format y but using a value in label give me wrong values ?

Thx for you help. 
Ps: I love ggpubr ! greatjob

**Comment by kassambara** [comment]
Hi,

In the current version, the argument `label` should be a logical value or a column name in the data.

Find a reproducible R code below. 

```r
library(ggpubr)
```


- Create some data:

```r
# Create some data
df <- data.frame(supp=rep(c("VC", "OJ"), each=3),
                  dose=rep(c("D0.5", "D1", "D2"),2),
                  len=c(6.8, 15, 33, 4.2, 10, 29.5))
print(df)
```

<pre>
  supp dose  len
1   VC D0.5  6.8
2   VC   D1 15.0
3   VC   D2 33.0
4   OJ D0.5  4.2
5   OJ   D1 10.0
6   OJ   D2 29.5
</pre>


- Create barplot:


This works:  

```r
# Plot "len" by "dose" and change color by a second group: "supp"
# Add labels inside bars
ggbarplot(df, x = "dose", y = "len",
          fill = "supp", color = "supp", palette = "Paired",
          label = TRUE,
          position = position_dodge(0.8))
```

This also works:

```r
ggbarplot(df, x = "dose", y = "len",
          fill = "supp", color = "supp", palette = "Paired",
          label = "len",
          position = position_dodge(0.8))
```

![marplot-with-label](https://user-images.githubusercontent.com/3313355/47132856-62df3700-d2a6-11e8-984d-b800b051f83b.png)


- Format the label using the arguments `lab.nb.digits`


```r
ggbarplot(df, x = "dose", y = "len",
          fill = "supp", color = "supp", palette = "Paired",
          label = "len", lab.nb.digits = 0,
          position = position_dodge(0.8))
```

![barplot-format-label](https://user-images.githubusercontent.com/3313355/47133438-10ebe080-d2a9-11e8-973d-05f0822856df.png)



Note that, you can also use a formatted supplementary column in your data; and, this new column name can be specify as label value when calling the function ggbarplot().

We'll keep this issue open, to update ggbarplot, so that it can correctly accept a character vector as label.

Thanks

**Comment by bvprod2** [comment]
thx !!!
