### ISSUE TITLE
ggline is not facetting correctly

### ISSUE THREAD

**Issue by jcpsantiago** [kassambara/ggpubr#19]
I may have found another bug. When using facet_wrap or facet_grid with ggline, both plots show the same lines, even though using the option "mean_se" shows the correct errors.

[rep_script.txt](https://github.com/kassambara/ggpubr/files/1196209/rep_script.txt)
![rplot](https://user-images.githubusercontent.com/789796/28909118-5815fbe0-7827-11e7-85b0-e38aa688c342.jpeg)
![rplot01](https://user-images.githubusercontent.com/789796/28909116-58155762-7827-11e7-816c-72bec76e0df0.jpeg)
![rplot02](https://user-images.githubusercontent.com/789796/28909117-5815f762-7827-11e7-985e-4c83930dfe9c.jpeg)

I've been using your awesome package a lot, thanks for your work!

**Comment by kassambara** [comment]
Hi,
Thank you for pointing this out. It's not a bug but I should clarify it in the documentation.

When using the argument add = "mean" or "mean_se", ...., the `ggline()` function computes summary statistics by groups.

Applying the traditional ggplot2::facet_xxx() on the output of ggline( ), in the situation where you used the option `add`, doesn't work  because ggplot2::facet_xxx()  considers the whole initial data set not the summary data sets.

A solution is to specify the argument `facet.by` in the ggline() function:

```r
df %>%
  ggline(x = "sampleNum", y = "value",
         color = "tx", add = "mean_se",
         facet.by = "sex",
         palette = "jco"
         ) 
```

The output looks like this:

![ggline-and-facet](https://user-images.githubusercontent.com/3313355/28921610-ec973ade-7856-11e7-82ef-473cf4b0789d.png)

**Comment by jcpsantiago** [comment]
Great, thanks! I was not not aware of that option. Keep up the good work!
