### ISSUE TITLE
stat_compare_means doesn't work with facets and groups/fills

### ISSUE THREAD

**Issue by BrianCollinss** [kassambara/ggpubr#232]
Here is my data: [LINK](https://drive.google.com/open?id=1oqLhErpvfEMyer0jUTaTdq8EGgV431L2)
Here is a sample of what I do:

```
    ggplot(data=Temp,aes(x=Site,y=SowDate,fill=Climate)) +
      geom_boxplot() +
      facet_grid(Cultivar~.) +
      stat_compare_means(label='p.signif',method='wilcox.test',
                         label.y=as.Date('1/7/2019',format='%d/%m/%Y'),size=2.2,ref.group='2005',na.rm=T)

Warning messages:
1: Computation failed in `stat_compare_means()`:
missing value where TRUE/FALSE needed 
2: Computation failed in `stat_compare_means()`:
missing value where TRUE/FALSE needed 
3: Computation failed in `stat_compare_means()`:
missing value where TRUE/FALSE needed 
```

I have the same problem when there are more than two groups (here, Climates) in the data.

**Comment by kassambara** [comment]
I c'ant reproduce your example because the data are no longer available. The following blog posts might help to add p-values onto grouped ggplots

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
