### ISSUE TITLE
fill error trying to plot p_values on facet boxplot

### ISSUE THREAD

**Issue by bholt20** [kassambara/ggpubr#266]
Not sure if this is a ggpubr or rstatix question. I continue to get an error (Error: Aesthetics must be either length 1 or the same as the data (3): fill) when trying to add p values onto a facet plot.

Here is a similar code that reproduces the error: 
test<-runif(30, min = 10, max = 30)
test2<-runif(30, min = 5, max = 15)
testa<-test[1:10]
testb<-test[11:20]
testc<-test[21:30]

test2a<-test2[1:10]
test2b<-test2[11:20]
test2c<-test2[21:30]

x<-c(rep('test', 10), rep('test2', 10))
x<-rep(x, 3)       
A<-c(testa, test2a)
B<-c(testb, test2b)        
C<-c(testc, test2c)
tot<-c(A, B, C)

lett<-c(rep('A', 20), rep('B', 20), rep('C', 20))
length(tot)
blah<-data.frame(x=x, lett=lett, tot=tot)

blah.p<-ggplot(blah, aes(x = x, y = tot, fill=x)) + facet_wrap(~lett, strip.position = 'bottom') +geom_boxplot()+theme_classic(base_size = 10, base_family = "")

blah.stat<-blah %>% group_by(lett) %>% wilcox_test(data = ., tot~x) %>% adjust_pvalue(method = "bonferroni") %>% add_significance("p.adj")
?add_y_position
blah.stat<- blah.stat %>% add_y_position(fun = 'max')

blah.p + stat_pvalue_manual(blah.stat, label = 'p.adj.signif', tip.length = 0.01)

Thanks for the help!

**Comment by kassambara** [comment]
This issue is from the way you are using ggplot verbs for creating the colored box plots.

Please use this: 

```r
blah.p <- ggplot(blah, aes(x = x, y = tot)) +
  facet_wrap(~lett, strip.position = "bottom") + 
  geom_boxplot(aes(fill = x)) + 
  theme_classic(base_size = 10, base_family = "")
```

Instead of:

```r
blah.p <- ggplot(blah, aes(x = x, y = tot, fill = x)) +
  facet_wrap(~lett, strip.position = "bottom") + 
  geom_boxplot(aes(fill = x)) + 
  theme_classic(base_size = 10, base_family = "")
```

As you know any aesthetics specified in the core function `ggplot()` will be applied on all the subsequent layers (here geom_boxplot and stat_pvalue_manual()).  This is overkilling. 

In your example, you only want to change the fill color of  box plots by groups; so consider specifying the `fill` aesthetic  in the geom_boxplot() function only otherwise ggplot will also look for this aesthetic in the stats results. The problem is that this variable is not present in the stat results.

The following reproducible example should work in your R session:


``` r
library(ggpubr)
library(rstatix)

df <- ToothGrowth
df$dose <- as.factor(df$dose)

bxp <- ggboxplot(df, x = "supp", y = "len", fill = "supp") +
  facet_wrap(~dose, strip.position = "bottom") 

res.stat <- df %>% 
  group_by(dose) %>% 
  wilcox_test(data = ., len ~ supp) %>% 
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")


res.stat <- res.stat %>% 
  add_xy_position(x = "supp", fun = "max") 

bxp + 
  stat_pvalue_manual(
    res.stat, label = "p.adj.signif", tip.length = 0.01
  )
```

![](https://i.imgur.com/XSSFY4M.png)

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by bholt20** [comment]
Yes, worked perfectly. thanks!

**Comment by jaydoc** [comment]
`df <- ToothGrowth`

`df$dose <- as.factor(df$dose)`

`df$group <- factor(rep(c("grp1", "grp2"), 30))`

`bxp <- ggboxplot(
  df, x = "supp", y = "len", fill = "dose", 
  palette = "jco", facet.by = "group", bxp.errorbar = "TRUE"
)`

`stat.test <- df %>%
  group_by(supp, group) %>%
  t_test(len ~ dose)`

`stat.test <- stat.test %>%
  add_xy_position(x = "supp", dodge = 0.8)`


`bxp + 
  stat_pvalue_manual(
    stat.test, label = "p", tip.length = 0.01,
    hide.ns = TRUE
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.01, 0.1)))`

This code produces the error  **Error in FUN(X[[i]], ...) : object 'dose' not found**

When I choose to use `color` instead of `fill` for the `dose` variable the code works perfectly. 
Why would it not work when using 'fill`? Thanks for any help.

**Comment by kassambara** [comment]
@jaydoc the root cause is the option bxp.errorbar = TRUE

**Comment by kassambara** [comment]
fixed now

**Comment by purisuto** [comment]
Sorry, but thanks so much for this answer! This problem was breaking my mind!
