### ISSUE TITLE
Avoid masking the name `extract`, or include a help topic for it

### ISSUE THREAD

**Issue by ning-y** [kassambara/ggpubr#321]
First of all, thank you for all your work in developing and maintaining this package.

I often load ggpubr after tidyverse, which causes *tidyr::extract* to be masked by the *extract* (referring to the primitive '[', I think?) of ggpubr.

```
> library(ggpubr)
Loading required package: magrittr

Attaching package: ‘magrittr’

The following object is masked from ‘package:purrr’:

    set_names

The following object is masked from ‘package:tidyr’:

    extract
```

This evening I spent quite a while wondering why *extract* in my script wasn't working as intended. I hadn't realised the masking until I checked the package loading messages, because I usually check for masking by going through the help topics, e.g. `?extract`, but ggpubr doesn't add a help topic for extract when it masks that name.

Now, this is totally my bad. I should have checked the package load messages. But it would be nice, for quality of life, if either
- ggpubr does not mask extract, or
- a help topic is added for ggpubr's extract.

**Comment by kassambara** [comment]
Hi, Which version of ggpubr do you have? 

The function `set_names()` and `extract()` are not included in ggpubr R package but in the `magrittr` R package, which is automatically loaded by old  versions of ggpubr to make the pipe `%>%` available. 

Normally, with the latest version of ggpubr on CRAN (v = 0.4.0) you shouldn't have this issue, because the magrittr package is no longer automatically loaded by ggpubr v0.4.0; we simply reexport/load the pipe function from magrittr.

Please, let me know if your issue is fixed with the latest ggpubr version, thanks!

**Comment by ning-y** [comment]
I am on 0.2.5, so I've probably reported an issue on an outdated version of ggpubr. Thanks for getting back, and I'll consider this solved!
