### ISSUE TITLE
p-value label cut off when using facets

### ISSUE THREAD

**Issue by grst** [kassambara/ggpubr#331]
When I create a plot with facets and multiple comparisons, the p-value lables are cut off. 

### Repex
```R
library(ggplot2)
library(ggpubr)

ggplot(diamonds, aes(x=cut, y=carat)) +
   facet_wrap(~clarity) +
   geom_jitter() + 
   stat_compare_means(comparisons=list(c(1,2), c(1,5)), method="wilcox")
```

![image](https://user-images.githubusercontent.com/7051479/90630910-27a34b80-e222-11ea-8656-a59dc38344c4.png)

### Software versions
 * ggplot 3.3.2
 * ggpubr 0.4.0

### Additional Information
Manually setting `ylim` helps, but I cannot do that when using `scales="free"`.

**Comment by kassambara** [comment]
Using the combination of the ggplot functions `scale_y_continuous()` and `expansion()` should solve this issue; see example of R codes at:  [GGPLOT Facet: How to Add Space Between Labels on the Top of the Chart and the Plot Border](https://www.datanovia.com/en/blog/ggplot-facet-how-to-add-space-between-labels-on-the-top-of-the-chart-and-the-plot-border/)

Let me know if it works, so that we can close the issue. 

```r
library(ggplot2)
library(ggpubr)

ggplot(diamonds, aes(x=cut, y=carat)) +
  facet_wrap(~clarity) +
  geom_jitter() + 
  stat_compare_means(comparisons=list(c(1,2), c(1,5)), method="wilcox") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)))
```
