### ISSUE TITLE
How I keep the original test after transformed ylim

### ISSUE THREAD

**Issue by guokai8** [kassambara/ggpubr#36]
Here is the problem, if I just use 
```
ggviolin(df,"group","Length",color="group",palette = c("#00AFBB", "#E7B800", "#FC4E07"),
         add = "boxplot",add.params = list(width=0.1))+
  scale_x_discrete(limits=c("de","un","st"),
                   labels=c("D", "NC", "S"))+
  stat_compare_means(comparisons = my_comparisons,method = "t.test",paired = F)+
  theme_light(base_size = 15)+
  ylab("Length")+theme(legend.position = "none")+
  xlab("")
```

![rplot](https://user-images.githubusercontent.com/9088155/30704120-4da120fc-9eb7-11e7-83ff-aef6b2ca7ef3.png)

I will get the results there should not significant difference between group D and S
However, when I transformed the ylim with log10 I just want to make the distribution looks more beautiful. the results will change totally.
```
ggviolin(df,"group","Length",color="group",palette = c("#00AFBB", "#E7B800", "#FC4E07"),
         add = "boxplot",add.params = list(width=0.1))+
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)))+
  scale_x_discrete(limits=c("destabilized","unchanged","stabilized"),
                   labels=c("D", "NC", "S"))+
  stat_compare_means(comparisons = my_comparisons,method = "t.test",paired = F)+
  theme_light(base_size = 15)+
  ylab("Length")+theme(legend.position = "none")+
  xlab("")
```
![rplot01](https://user-images.githubusercontent.com/9088155/30704166-7a44be16-9eb7-11e7-820e-40290f21075e.png)
I just wonder how can I keep the original t.test results to show on the figure with ylim transformed.
Thanks!
Kai

**Comment by kassambara** [comment]
When transforming axis scales and limits, it's preferred to use the cartesian coordinate systems instead of the `scale_xxx()` functions.

For examples,
   
- For changing axis limits, use `coord_cartesian()` instead of using `scale_x_continuous()/scale_y_continuous()`
- For log transformation, use `coord_trans()` instead of using `scale_x_continuous()/scale_y_continuous()` or `scale_x_log10() / scale_y_log10()`.
   
   
In most cases you would not see the difference, but if you fit anything to the data the functions `scale_x_continuous() / scale_y_continuous()` would probably change the fitted values.
    
    
Examples of R code: 

Default plots:

```r
library(ggpubr)
p <- ggviolin(iris, x = "Species", y = "Sepal.Length",
              add = "boxplot", add.params = list(fill = "white"),
              fill = "Species", palette = "jco")

my_comparisons = list(
  c("setosa", "versicolor"),
  c("versicolor", "virginica")
  )
# Default comparison
p + stat_compare_means(
  comparisons = my_comparisons, method = "t.test"
)
```

![rplot](https://user-images.githubusercontent.com/3313355/32263828-d755e8ac-bedb-11e7-9ae1-c0684e50224a.png)


```r
# Axis transformation using coord_trans
# Doesn't affect the test
p + stat_compare_means(
  comparisons = list(c("setosa", "versicolor"), c("versicolor", "virginica")),
  method = "t.test"
) +
  coord_trans(y = "log2")
```
![rplot20](https://user-images.githubusercontent.com/3313355/32263842-eb0acf98-bedb-11e7-82a4-a415cb1090b6.png)


```r
# Axis transformation using scale_y_continuous
# Affects the test
p + stat_compare_means(
  comparisons = list(c("setosa", "versicolor"), c("versicolor", "virginica")),
  method = "t.test"
) +
  scale_y_continuous(trans = "log2")
```
![rplot21](https://user-images.githubusercontent.com/3313355/32263869-07369012-bedc-11e7-89ef-3ddfeedc5283.png)

**Comment by adomingues** [comment]
Very interesting @kassambara , I was not aware of the difference. Cheers.

I am wondering if there is a way of creating a plot with the stats, untransformed data, retrieve the stats, and add them to a second plot with transformed data. I am asking because visually transforming the axis does not work for my purposes. I played with the ggplot object layers for a while but got nowhere.

**Comment by adomingues** [comment]
There is an to solve this in this in [here](https://github.com/kassambara/ggpubr/issues/65#issuecomment-395137940).
