### ISSUE TITLE
label_size in ggarrange() ?

### ISSUE THREAD

**Issue by G-Thomson** [kassambara/ggpubr#38]
In `cowplot `the `plot.grid()` function has the `label_size` option to change the size of labels?

Could this be implemented in `ggarrange()` too?

**Comment by G-Thomson** [comment]
see pull request [#39](https://github.com/kassambara/ggpubr/pull/39)

**Comment by kassambara** [comment]
Hi,

as the argument `font.label` is  used in many ggpubr functions (see ggboxplot) to customize labels, I keep the same naming convention for `ggarrange()`.

New arguments in `ggarrange()` to customize plot labels:
    - font.label
    - label.x and label.y
    - hjust and vjust


Examples:  

```r
library(ggpubr)
data("ToothGrowth")
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Create some plots
# ::::::::::::::::::::::::::::::::::::::::::::::::::
bxp <- ggboxplot(df, x = "dose", y = "len",
    color = "dose", palette = "jco")
dp <- ggdotplot(df, x = "dose", y = "len",
    color = "dose", palette = "jco")
dens <- ggdensity(df, x = "len", fill = "dose", palette = "jco")

# Arrange
# ::::::::::::::::::::::::::::::::::::::::::::::::::
ggarrange(bxp, dp, dens, ncol = 2, nrow = 2,
          labels = c("A", "B", "C"),
          font.label = list(size = 16, color = "red"))
```

![rplot](https://user-images.githubusercontent.com/3313355/31351951-4e0caf0a-ad2d-11e7-8ff5-c713652fd9f0.png)

**Comment by PabloAFi** [comment]
Nice. It really works

**Comment by blueandtanit** [comment]
Hi, I'm beginner with R and I'm learning for my thesis data analysis (and fancy custom presentation of results), I want to know how can i center the graphic labels, because it looks on the y axis at the boxplot.

I'm using this code:
ggarrange(q, s, u, w, y, d, f, h, j, ncol = 3, nrow = 3, 
          labels = c("LT", "LA", "LE", "TD", "LH", "L1", "L2", "L3", "L1L2"),
          font.label = list(size = 16, color = "black"), common.legend = TRUE, legend = "top")
for the plots (example):
p<-ggplot(data, aes(x=Embalse, y=LT, fill=Embalse)) +
  geom_boxplot()

what's wrong?
thanks for your help.
