### ISSUE TITLE
p-values different in t.test through stat_compare_means and t.test in R

### ISSUE THREAD

**Issue by cchien1** [kassambara/ggpubr#44]
Hi, 
I am not sure what kind of t-test is performed in ggpubr. It is not a big deal, however, I needed to get the t-statistic for these tests on multiple plots. This is not a function in stat_compare_means so I tried to perform the t.test function (Welch Two Sample t-test) which gave me different p-values than what was printed in ggpubr.

1. Is there a way to print the t-statistic through ggpubr?

2. Is there a way to use the Welch Two Sample t-test in ggpubr?

Thanks so much! Looking forward to hearing from you.

Claudia

**Comment by kassambara** [comment]
Hi,

By default, ggpubr performs a wilcoxon test.

For a t.test, specify the argument method = "t.test":  


```{r}
# Load data
data("ToothGrowth")
head(ToothGrowth)
p <- ggboxplot(ToothGrowth, x = "supp", y = "len",
               color = "supp", palette = "npg")
p + stat_compare_means(method = "t.test")
```
![rplot](https://user-images.githubusercontent.com/3313355/31775301-808008ac-b4e8-11e7-95ed-0929a34b284b.png)

    
As you can see below, the output of ggpubr is the Welch t-test: 
   
```{r}
t.test(len ~ supp, data = ToothGrowth)
```
<pre>

	Welch Two Sample t-test

data:  len by supp
t = 1.9153, df = 55.309, p-value = 0.06063
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.1710156  7.5710156
sample estimates:
mean in group OJ mean in group VC 
        20.66333         16.96333 
</pre>

Please, make sure that you have the latest developmental version of ggpubr.

**Comment by cchien1** [comment]
Thanks so much for your help... I don't know why I still don't have this.. I was selecting "t.test". Does it change if you use facet_wrap with a different variable?
mucca_dftest <- DF %>%
                gather("Method","Value",c("MUCCA","CCV","TCV") ) %>%
                mutate(Method = factor(Method, 
                         levels = c("MUCCA","CCV","TCV") ) )

ggplot(data = mucca_dftest, aes(x=Group, y=Value, alpha=0.3)) +
  geom_boxplot() + labs(x="",y="") +
  geom_quasirandom(dodge.width=.9) +
  facet_wrap( ~ Method, scales = "free", ncol = 3) 
mucca_group + stat_compare_means(method = "t.test", label = "p.format", label.x = 1.25) 

[Rplot1a_GroupComp_save.pdf](https://github.com/kassambara/ggpubr/files/1398924/Rplot1a_GroupComp_save.pdf)

t.test(subset(DF, Group=="HC")$MUCCA, subset(DF, Group=="NMO")$MUCCA)

	Welch Two Sample t-test

data:  subset(DF, Group == "HC")$MUCCA and subset(DF, Group == "NMO")$MUCCA
t = 3.4153, df = 44.907, p-value = 0.001362
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  2.599328 10.072851
sample estimates:
mean of x mean of y 
 76.32192  69.98583

**Comment by kassambara** [comment]
Your script is not reproducible as it doen't contain any demo data set, so that I can check the issue.

Please specify the argument `facet.by` in the function `ggboxplot()`.

- With a demo data set, it looks like this: 
   
```r
library(ggpubr)
p <- ggboxplot(ToothGrowth, x = "supp", y = "len",
               color = "supp", palette = "jco",
               add = "jitter",
               facet.by = "dose", short.panel.labs = FALSE)

p + stat_compare_means(method = "t.test", label = "p.format")
```

![rplot](https://user-images.githubusercontent.com/3313355/31849826-3c3d6d80-b649-11e7-93c9-6fd0ad248482.png)

- The standard t-test is as follow:  
   
```r
subset(ToothGrowth, dose == "0.5") %>%
  t.test(len ~ supp, data = .)
```

<pre>

	Welch Two Sample t-test

data:  len by supp
t = 3.1697, df = 14.969, p-value = 0.006359
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 1.719057 8.780943
sample estimates:
mean in group OJ mean in group VC 
           13.23             7.98 
</pre>

- Do all the pairwise comparisons at once

```r
compare_means(len ~ supp, data = ToothGrowth,
              group.by = "dose",
              method = "t.test")
```

<pre>
# A tibble: 3 x 9
   dose   .y. group1 group2           p       p.adj p.format p.signif method
  <dbl> <chr>  <chr>  <chr>       <dbl>       <dbl>    <chr>    <chr>  <chr>
1   0.5   len     OJ     VC 0.006358607 0.012717214   0.0064       ** T-test
2   1.0   len     OJ     VC 0.001038376 0.003115128   0.0010       ** T-test
3   2.0   len     OJ     VC 0.963851589 0.963851589   0.9639       ns T-test
</pre>
