### ISSUE TITLE
Suppress `geom_smooth()` using formula 'y ~ x' messages in `ggscatter()`

### ISSUE THREAD

**Issue by dchiu911** [kassambara/ggpubr#488]
I think we can suppress the persistent
```
 `geom_smooth()` using formula 'y ~ x'
```
messages (from `ggscatter()` for e.g.) by adding the following after [this line](https://github.com/kassambara/ggpubr/blob/master/R/ggscatter.R#L284):
```r
option[["formula"]] <- y ~ x
```

**Comment by aphalo** [comment]
The behaviour of `geom_smooth()` depends on the number of observations. Probably it would be best to set `method = lm` to avoid it switching to using splines. Anyway, there have been no commits at this repo for 2 years and no answers from the repo owner to issues raised or pull requests also for a very long time. I think the effort of learning the Grammar of Graphics and using 'ggplot2' and its extenssions through this grammar saves many of the headaches caused by "canned" plotting functions like those in 'ggpubr'.
