### ISSUE TITLE
How to set log scale but did not change the R and P value when using stat_cor?

### ISSUE THREAD

**Issue by xieduo7** [kassambara/ggpubr#505]
I want to set the log scale and perform correlation analysis using the original values.

The original plot:
```
data(cars)
p <- ggscatter(cars, x = "speed", y = "dist") + 
  stat_cor(method = "pearson")
p
```
![image](https://user-images.githubusercontent.com/35059160/199014563-9d85ca93-d902-46f0-949f-b00836ff47d6.png)

The plot using log10 scale:
```
q <- ggscatter(cars, x = "speed", y = "dist") + 
  stat_cor(method = "pearson") + yscale("log10")
q
```
![image](https://user-images.githubusercontent.com/35059160/199014705-933bb206-47fd-453d-a380-f4fec0f9ed22.png)

However, after I changed to the log scale axis, the R and P value also changed. **How can I only change the axis to log scale axis but did not change the R and P value?**

Thank you!

Best,
Duo

**Comment by kassambara** [comment]
Related to #36

**Comment by kassambara** [comment]
When transforming axis scales and limits, it's preferred to use the cartesian coordinate systems instead of the `scale_xxx()` functions.

For examples,
   
- For changing axis limits, use `coord_cartesian()` instead of using `scale_x_continuous()/scale_y_continuous()`
- For log transformation, use `coord_trans()` instead of using `scale_x_continuous()/scale_y_continuous()` or `scale_x_log10() / scale_y_log10()`.
   
   
In most cases you would not see the difference, but if you fit anything to the data the functions `scale_x_continuous() / scale_y_continuous()` would probably change the fitted values. `coord_trans()` is different to scale transformations in that it occurs after statistical transformation and will affect the visual appearance of geoms. 
    
    
Examples of R code: 

``` r
suppressPackageStartupMessages(library(ggpubr))

ggscatter(cars, x = "speed", y = "dist") + 
  stat_cor(method = "pearson") + 
  coord_trans(y = "log10")
```

![](https://i.imgur.com/Ufo8yYj.png)
