### ISSUE TITLE
Hide non-significant pairwise comparisons

### ISSUE THREAD

**Issue by mathykathy26** [kassambara/ggpubr#60]
Is there an intuitive way to hide or leave out brackets for non-significant pairings? For example, below are two groups that are not significantly different at the 0.05 level and I would like for it to not show the bracket and p-value. This would be generalizable to more than 2 groups so that significant pairing are the only ones that show up.

Thanks!

``` r
library(ggpubr)

# Load data
data("ToothGrowth")
head(ToothGrowth)

str(ToothGrowth)

my_comparisons <- list( c("OJ","VC") )
ggboxplot(ToothGrowth, x = "supp", y = "len",
          color = "dose", palette = "npg")+
  # Would like to hide non-significant pairwise comparisons
  stat_compare_means(comparisons = my_comparisons, label.y = c(40), hide.ns = TRUE)+
  stat_compare_means(label.y = 45)     # Add global Anova p-value
```

**Comment by kassambara** [comment]
In the current version, there is no automatic solution hide the brackets.

A  semi-manual solution:

If a given comparison, say C vs D, is not significant, just remove the comparison from the list.

For example use this: `my_comparisons = list(c("A", "B"), c("B", "C"))` instead of `my_comparisons = list(c("A", "B"), c("B", "C"), c("C", "D")))`

**Comment by jacorvar** [comment]
Hi, have you already added this functionality?
In my case, I have many plots I'd like to remove the non-significant p-values automatically, so It isn't therefore feasible to remove them manually.

Thanks

**Comment by kassambara** [comment]
yes, you can hide automatically non significant p-values: [see example on datanovia](https://www.datanovia.com/en/blog/how-to-perform-t-test-for-multiple-groups-in-r/)

**Comment by nick-youngblut** [comment]
That's for manual plotting of p-values but is there anything for automatically plotting p-values with `stat_compare_means(comparisons = my_comparisons)`? 

Also, it could be helpful to include the following code in an example to show an easy way of getting all pairwise combinations to test:

```
my_comparisons = combn(as.character(unique(df$diet)), 2, simplify=FALSE) 
p <- ggboxplot(df, x = "diet", y = "mean_resid", 
              palette = "jco", add = "jitter") + 
    stat_compare_means(comparisons = my_comparisons) 
```

**Comment by MatteoSchiavinato** [comment]
I would also really appreciate if you added a functionality similar to `hide.ns=TRUE` which hides the non significant brackets declared in comparisons. 

I have automatic plotting embedded in a pipeline so I cannot afford hardcoding my list of comparisons, which is autocompiled based on some analysis criteria. 

I think it would be extremely useful!

**Comment by MatteoSchiavinato** [comment]
I found an automated workaround that some people might benefit from.
My data looks like this:
```
        Timepoint Treatment Richness
FCD14A1       D14         A      185
FCD14A2       D14         A      286
FCD14A3       D14         A      316
FCD14A4       D14         A      234
FCD14B1       D14         B      311
FCD14B2       D14         B      322
FCD14B3       D14         B      278
FCD14B4       D14         B      291
```

I want to  calculate t-tests between the richness values of all possible pairs of treatments, that is, my "Treatment" column in the dataframe above. Hence:

1. I compute all pairwise combinations of treatments, using `combn()` on `x$Treatment` and specifying `2` elements at once. `simplify=FALSE` prevents the output from being different than a `list()`.
2. I declare an empty list to which I will append my significant combinations.
3. Inside the `for` loop, which I do iterating over the length of `Comparisons`, I extract the `pair`. That is a 2-elements vector containing a pair of treatments that are under assessment in this iteration of the loop. Say "A" and "B" for example. 
4. I then extract all those lines belonging to either one of those treatments using normal `R` syntax, and I `rbind()` them together to form a smaller matrix called `tmp`. I then convert it to a `data.frame()`. 
5. I convert the element which I will use for the `T.test` to a `factor()`, so that it can have levels. As levels, I just take the `unique()` set of elements describing it. In this example, it would be "A" and "B". 
6. I calculate the t-test using R's `t.test()` function.
7. I extract the p value from the results namespace.
8. If I deem it significant, that is for me < 0.05, I append that `pair` to the list `Filtered`.

```
Comparisons <- combn(x$Treatment, 2, simplify=FALSE)
Filtered <- list()

k = 0
for (i in 1:length(Comparisons)) {
	pair <- Comparisons[[i]]
	tmp <- rbind(x[(x["Timepoint"]==ti) & (x["Treatment"]==pair[1]), ], x[(x["Timepoint"]==ti) & (x["Treatment"]==pair[2]), ])
	tmp <- as.data.frame(tmp)
	tmp$Treatment = factor(tmp$Treatment, levels=unique(tmp$Treatment))
	res <- t.test(Richness ~ Treatment, data=tmp)
	if (res$p.value < 0.05) {
		k = k + 1
		Filtered[[k]] <- pair
	}
}

```

The `Filtered` list can then be passed to `stat_compare_means()`, like this:
```
stat_compare_means(comparisons=Filtered)
```

Worked perfectly for me.

**Comment by eyal-gi** [comment]
> I found an automated workaround that some people might benefit from.
> My data looks like this:
> 
> ```
>         Timepoint Treatment Richness
> FCD14A1       D14         A      185
> FCD14A2       D14         A      286
> FCD14A3       D14         A      316
> FCD14A4       D14         A      234
> FCD14B1       D14         B      311
> FCD14B2       D14         B      322
> FCD14B3       D14         B      278
> FCD14B4       D14         B      291
> ```
> 
> I want to calculate t-tests between the richness values of all possible pairs of treatments, that is, my "Treatment" column in the dataframe above. Hence:
> 
> ```
> Comparisons <- combn(x$Treatment, 2, simplify=FALSE)
> Filtered <- list()
> 
> k = 0
> for (i in 1:length(Comparisons)) {
> 	pair <- Comparisons[[i]]
> 	tmp <- rbind(x[(x["Timepoint"]==ti) & (x["Treatment"]==pair[1]), ], x[(x["Timepoint"]==ti) & (x["Treatment"]==pair[2]), ])
> 	tmp <- as.data.frame(tmp)
> 	tmp$Treatment = factor(tmp$Treatment, levels=unique(tmp$Treatment))
> 	res <- t.test(Richness ~ Treatment, data=tmp)
> 	if (res$p.value < 0.05) {
> 		k = k + 1
> 		Filtered[[k]] <- pair
> 	}
> }
> ```
> 
> **explained:**
> 
> 1. I compute all pairwise combinations of treatments, using `combn()` on `x$Treatment` and specifying `2` elements at once. `simplify=FALSE` prevents the output from being different than a `list()`.
> 2. I declare an empty list to which I will append my significant combinations.
> 3. Inside the `for` loop, which I do iterating over the length of `Comparisons`, I extract the `pair`. That is a 2-elements vector containing a pair of treatments that are under assessment in this iteration of the loop. Say "A" and "B" for example.
> 4. I then extract all those lines belonging to either one of those treatments using normal `R` syntax, and I `rbind()` them together to form a smaller matrix called `tmp`. I then convert it to a `data.frame()`.
> 5. I convert the element which I will use for the `T.test` to a `factor()`, so that it can have levels. As levels, I just take the `unique()` set of elements describing it. In this example, it would be "A" and "B".
> 6. I calculate the t-test using R's `t.test()` function.
> 7. I extract the p value from the results namespace.
> 8. If I deem it significant, that is for me < 0.05, I append that `pair` to the list `Filtered`.
> 
> The `Filtered` list can then be passed to `stat_compare_means()`, like this:
> 
> ```
> stat_compare_means(comparisons=Filtered)
> ```
> 
> Worked perfectly for me.

Hi, can you maybe explain what is the 'ti' in your code?

**Comment by MatteoSchiavinato** [comment]
It's the timepoint. I forgot to define it in the example, but in this case it would be "D14".

**Comment by Zhuang-WUR** [comment]
> I would also really appreciate if you added a functionality similar to `hide.ns=TRUE` which hides the non significant brackets declared in comparisons.
> 
> I have automatic plotting embedded in a pipeline so I cannot afford hardcoding my list of comparisons, which is autocompiled based on some analysis criteria.
> 
> I think it would be extremely useful!

Me too, I have been searching a solution forever online.

**Comment by iamnicogomez** [comment]
I am also wondering if there's anyway to do this. The brackets remaining after the "ns" are useless and seem like I've omitted something in my graphing.

**Comment by Shari51** [comment]
It would be great to add this please because workarounds don't work on facetted plots!

**Comment by RoniKeshet** [comment]
![image](https://user-images.githubusercontent.com/77229922/187895026-5b968f59-5a3d-48f1-ad65-42f950e0065e.png)
the issue is still there... 
stat_compare_means( comparisons =all_compaires, label = "p.signif", hide.ns = TRUE, method = "wilcox.test", paired = FALSE)
this is the commend i use, is there a fix in latter versions?

**Comment by kassambara** [comment]
(**Note: This issue is closed. If you have any questions please consider opening a new issue**)

Please consider using the latest (dev) version of `ggpubr`  which contains now the function [geom_pwc()](https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html) with lot of possibilities compared `stat_compare_means()`. stat_compare_means() will be progressively updated to be a wrapper around `geom_pwc()`.

## Examples using `geom_pwc()`: 

``` r
suppressPackageStartupMessages(library("ggpubr"))

df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Create a basic box plot
#:::::::::::::::::::::::::::::::::::::::
# Add p-values. The default method is the Wilcoxon test
bxp <- ggboxplot(df, x = "supp", y = "len") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))
bxp + geom_pwc(method = "t_test")
```

![](https://i.imgur.com/ZVd5wjq.png)

``` r

# Hide NS
bxp + geom_pwc(method = "t_test", hide.ns = TRUE)
```

![](https://i.imgur.com/fIl6xsz.png)

``` r


# Facet
#:::::::::::::::::::::::::::::::::::::::
# Change the label
# Create a ggplot facet
bxp + 
  geom_pwc(method = "t_test", label = "p.signif") +
  facet_wrap(~dose)
```

![](https://i.imgur.com/0lW1Fet.png)

``` r


# Hide NS
bxp + 
  geom_pwc(method = "t_test", label = "p.signif", hide.ns = TRUE) +
  facet_wrap(~dose)
```

![](https://i.imgur.com/lOk8JQC.png)

``` r

# Show p-values and significance
# and hide.ns
bxp + 
  geom_pwc(method = "t_test", label = "{p.format}{p.signif}",
           hide.ns = TRUE) +
  facet_wrap(~dose)
```

![](https://i.imgur.com/TsGbccy.png)

``` r


# More examples
#:::::::::::::::::::::::::::::::::::::::
ggboxplot(df, x = "dose", y = "len")  +
  geom_pwc(label = "{p.format}{p.signif}") +
  facet_wrap(~supp)
```

![](https://i.imgur.com/ikUb1bO.png)

``` r

# Hide NS
ggboxplot(df, x = "dose", y = "len")  +
  geom_pwc(label = "{p.format}{p.signif}", hide.ns = TRUE) +
  facet_wrap(~supp)
```

![](https://i.imgur.com/sjhAPfE.png)


## Read more

- [geom_pwc(): Add Pairwise Comparisons P-values to a GGPlot](https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html)
- [Add manually p-values to ggplots using rstatix and ggpubr](https://www.datanovia.com/en/?s=rstatix&search-type=default)
