### ISSUE TITLE
stat_compare_means: can we set font size of p value label?

### ISSUE THREAD

**Issue by shenwei356** [kassambara/ggpubr#69]
Hi, Dear @kassambara ,

Thank you for this great package, it's really help a lot in my work.

When using `stat_compare_means`, I tried to adjust the font size of p-value label, but didn't find a way from package API (I also tried `label.size` of `geom_label` ) and Github issues. 

Maybe I didn't find the right way. Is this available, so is space between tips?

Wei

**Comment by shenwei356** [comment]
Another suggestion: `hide.ns` only hide the text label, the lines are still shown.

**Comment by kassambara** [comment]
- to change p-value label size, specify the argument `size`.
- to hide ns follow our recommendation at: https://github.com/kassambara/ggpubr/issues/40#issuecomment-412154321

**Comment by ShixiangWang** [comment]
Great package, thanks for this question and answer.

**Comment by gokceneraslan** [comment]
Stars disappear when label =  "p.signif" and size=20 are used together, any suggestions?

**Comment by AMechels** [comment]
Hi, 

Indeed great package! I use it all the time.

I have the same problem as @gokceneraslan 
> Stars disappear when label = "p.signif" and size=20 are used together, any suggestions?

Furthermore, I was wondering if it is possible to specifically change the size of the stars/p-values, without changing the size of the legend?

Thanks in advance!

**Comment by AMechels** [comment]
@gokceneraslan 
Hi, I had the same problem. 
I noticed that the size in stat_compare_means() is not the same "scale" as the size in theme(text=element_text(size=16)) from ggplot.
Secondly I also noticed that when the size of your stars is too big, they disappear.

This is what I used in order to drop the stars a bit lower and make them bigger. 
`stat_compare_means(label = "p.signif", method = "wilcox.test", paired = F, hide.ns = T, show.legend = F, size = 8, label.y = 0.7)`

Hope that helps!!
