### ISSUE TITLE
p.adj was replaced by p.format in the figure

### ISSUE THREAD

**Issue by spiralife** [kassambara/ggpubr#86]
I want to show the the adjusted p value using the below code, but the p.format was showed. 
Please help me. Thank you~ 

`ggboxplot(ilist, x="group", y="data",color = "group",palette = "jco") +
  stat_compare_means(label=p.adj),comparisons=comparisons2,p.adjust.method="fdr",method="wilcox.test",hide.ns = TRUE)   `

![1](https://user-images.githubusercontent.com/39084079/39800813-b6834a3e-539b-11e8-8f43-6bc33c2e2cb3.jpg)

![2](https://user-images.githubusercontent.com/39084079/39800809-ada4a200-539b-11e8-880b-d5457b27e67f.jpg)

And I tried the below codes, it did not work. 

`ggboxplot(ilist, x="group", y="data",color = "group",palette = "jco") +
 stat_compare_means(aes(label="p.adj"),comparisons=comparisons2,p.adjust.method="fdr",method="wilcox.test",hide.ns = TRUE) `

`ggboxplot(ilist, x="group", y="data",color = "group",palette = "jco") +
stat_compare_means(aes(label=format.pval(..p.adj.., digits = 3)),comparisons=comparisons2,p.adjust.method="fdr",method="wilcox.test",hide.ns = TRUE) `

PS: 
R version 3.5.0 (2018-04-23)
ggpubr_0.1.6

**Comment by kassambara** [comment]
Solution provided in #65. Thanks @dregele for your contributions!

**Comment by ETaSky** [comment]
@kassambara I would suggest to reopen this issue as a bug because it is a problem of the different nature as issue #65 , even though the solution provided in that thread could solve the issue here.

The reason is when there is a parameter "p.adjust.methods", people would expect the p value shown on the graph is adjusted whether or not it is adjusted across all comparisons or comparisons by facet (which is the issue raised in #65 ). In this case, the OP did not use facet, however the p value is still not properly shown, even after using `stat_compare_means(aes(label = ..p.adj..))`. I tested in my own data, this is still the case in ggpubr_0.2.999

I guess this is a simple fix since facet is not involved. In general, people may want the multiple comparisons be performed in each facet independently. So #65 is arguably not a bug.

Thanks!

**Comment by kassambara** [comment]
In the current version, when a list of comparisons is provided, the p-values are not adjusted. 

I'm working on this.  

@ETaSky: Following your comments, I wrote a page in ggpubr wiki showing a solution for [adding adjusted p-values](https://github.com/kassambara/ggpubr/wiki/Adding-Adjusted-P-values-to-a-GGPlot)

**Comment by ETaSky** [comment]
@kassambara Thanks for your prompt reply. I just took some time to study the code and argument description for stat_compare_means.R and found the following:
(1) Actually, p.adjust.method is not an argument for `stat_compare_means()`, although it is an argument for `ggpubr::compare_means()`. The `...` in the argument list of `stat_compare_means()` is just for `other arguments to pass to geom_text or geom_label.` So technically, p adjustment is not part of the function of stat_compare_means.
(2) When the users supply a list of comparisons, `stat_compare_means()` actually used `ggsignif::geom_signif`. And `ggsignif::geom_signif` did not include a way to adjust p value as well.

So I have to walk back my previous comment, this is not a bug, because it is not a function that exist. And consequently, there seems not to be a simple fix. Perhaps a few lines can be add into the ggsignif::significance_annotation.R code so that it can output adjust p value.

**Comment by kassambara** [comment]
Now, adjusted p-values can be easily added onto a ggplot using the rstatix and the ggpubr package.

Many examples are provided in the following blog posts:

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
