### ISSUE TITLE
how to break y axis to accommodate all data

### ISSUE THREAD

**Issue by mas192** [kassambara/ggpubr#93]
![image](https://user-images.githubusercontent.com/21248222/41579098-707a5d24-7363-11e8-8162-c70e6197a9ef.png)

Hi Kassambara,

I would really appreciate your help, I am plotting data from two independent groups and due to the large spread of data, my data at lower ends are squished as seen in the image, how would I break my y-axis so as to set say y-axis to 0 -30 and 50 - 90 for example. 

Here is my  script for your reference,

IL6_bar_point_plot = ggbarplot(IL6_data, x = "Treatment", y = "IL6_release", ylim = c(0, 150),
                               ylab = "IL6 release (ng/mg of protein) ",
                              add = c("mean_se", "jitter"),
                              color = "Microglia", palette = "npg",
                              legend = c( "right")) # Nature publication style palette

IL6_plot = facet(IL6_bar_point_plot, facet.by = "Microglia", 
      panel.labs.background = list(color = "white", fill = "white", linetype = "blank"),
      panel.labs.font = list(color = "white"))

I would super appreciate if you could help me with this and definitely acknowledge your help in my publication.

Thanks
Sam Joshva

**Comment by kassambara** [comment]
Hi,

Breaking the y axis is not something simple in ggplot2 (see [this discussion](https://stackoverflow.com/questions/7194688/using-ggplot2-can-i-insert-a-break-in-the-axis)).

However you can easily render the two y axis independents, so that each group has its own y axis scale. To do so, specify the argument `scales = "free_y"` in the function `facet()`.

What do you think about that?
